In [1]:
import pandas as pd

In [2]:
mush_df = pd.read_csv('training_mush.csv')
mush_df.head()

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,class
0,2,0,3,1,5,1,0,0,9,1,...,3,7,0,2,1,4,3,5,0,0
1,2,0,4,0,5,1,0,1,10,0,...,7,4,0,2,1,0,7,4,0,1
2,2,0,3,0,2,1,0,0,7,0,...,0,4,0,2,1,2,1,5,1,1
3,0,0,3,0,5,1,1,0,2,0,...,7,7,0,2,2,4,7,3,1,0
4,2,3,3,1,5,1,0,0,10,1,...,3,6,0,2,1,4,2,5,0,0

In [8]:
my_data = pd.DataFrame([{'type':'A','value':10},{'type':'A','value':14},{'type':'B','value':12},{'type':'B','value':23}])
my_data.head()
my_data[my_data['value']>10].median()

value    14.0
dtype: float64

In [22]:
my_stat = pd.read_csv('my_stat_na.csv')
my_stat['session_value'].fillna(0)
n_users_median = my_stat[my_stat['n_users']>=0]['n_users'].median()
print(n_users_median)

7.0

In [23]:
my_stat.fillna(0)
my_stat['n_users'] = my_stat['n_users'].apply(lambda n_users: n_users_median if (n_users<=0) else n_users)
my_stat

     group  n_users  session_value time
0      9.0      7.0            1.0    A
1     10.0      8.0            2.0    B
2     10.0      7.0            4.0    A
3     10.0      7.0            0.0    B
4      9.0      7.0           -1.0    B
5     11.0      7.0            0.0    B
6     10.0      7.0            NaN    B
7     10.0      1.0            0.0    B
8      9.0      3.0            0.0    B
9     11.0     11.0            0.0    A
10    10.0     11.0            1.0    B
11    10.0      5.0            0.0    A
12    10.0      7.0           -3.0    B
13    10.0      3.0            0.0    A
14    10.0      7.0            0.0    B
15    11.0     13.0            1.0    A
16    12.0      7.0            0.0    A
17     8.0      7.0            1.0    B
18    11.0      4.0            0.0    A
19     8.0      3.0            0.0    B
20     9.0     20.0            1.0    B
21    11.0      2.0           -3.0    B
22    10.0     13.0            0.0    A
23    11.0     11.0            2.0    B
24    10.0      7.0            0.0    A
25     9.0      7.0            1.0    A
26    12.0      7.0           -1.0    B
27    11.0      7.0            0.0    A
28    10.0     12.0            0.0    B
29    10.0     16.0            3.0    B
..     ...      ...            ...  ...
470   11.0      7.0           -2.0    B
471   10.0      6.0           -4.0    A
472   10.0      7.0            0.0    A
473   10.0      7.0            2.0    B
474   10.0      7.0           -3.0    A
475   10.0     17.0            0.0    A
476   11.0      7.0            2.0    B
477   10.0      7.0           -1.0    A
478   10.0      7.0           -3.0    A
479   11.0      2.0            2.0    B
480   10.0     15.0           -4.0    A
481   10.0      6.0           -3.0    A
482   11.0      9.0           -2.0    A
483   11.0      6.0            2.0    B
484   12.0      7.0            0.0    B
485   10.0     17.0           -1.0    B
486    8.0      7.0            1.0    A
487    9.0      7.0            4.0    B
488   11.0      3.0            0.0    B
489    9.0      4.0            NaN    B
490    9.0      3.0            NaN    A
491    9.0      7.0           -4.0    B
492   10.0      7.0           -1.0    B
493    9.0      3.0           -1.0    B
494   10.0     11.0           -1.0    A
495   10.0     14.0           -1.0    B
496   10.0      6.0           -1.0    A
497    7.0      7.0            0.0    A
498   11.0     16.0            0.0    A
499   10.0     15.0            0.0    A

[500 rows x 4 columns]